version: 2.1

parameters:
  OGGVERSION:
    type: string
    default: "1.3.5"
  VORBISVERSION:
    type: string
    default: "1.3.7"
  FLACVERSION:
    type: string
    default: "1.3.3"
  OPUSVERSION:
    type: string
    default: "1.3.1"
  MPG123VERSION:
    type: string
    default: "1.29.3"
  LAMEVERSION:
    type: string
    default: "3.100"        
  SNDFILE_VERSION:
    type: string
    default: "1.1.0"
  SNDFILENAME:
    type: string
    default: libsndfile-<< pipeline.parameters.SNDFILE_VERSION>>


jobs:
  build_libvorbis:
    macos:
      xcode: 13.3
    steps:
      - run:
          name: "Fetch library"
          command: curl -LO https://downloads.xiph.org/releases/ogg/libogg-<<pipeline.parameters.OGGVERSION>>.tar.gz
      - run:
          name: "Unpack library"
          command: tar zxvf libogg-<<pipeline.parameters.OGGVERSION>>.tar.gz
      - run:
          name: "Configure build"
          command: ./configure --disable-shared
          working_directory: ./libogg-<<pipeline.parameters.OGGVERSION>>
          environment:
            MACOSX_DEPLOYMENT_TARGET: 10.9
            ARCH: arm64
      - run:
          name: "Build"
          command: make -j8
          working_directory: ./libogg-<<pipeline.parameters.OGGVERSION>>
      - run:
          name: "Check architectures"
          command: file .libs/libogg.a
          working_directory: ./libogg-<<pipeline.parameters.OGGVERSION>>
workflows:
  build_mac_arm64:
    jobs:
      - build_libvorbis
